apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:latest
        #command: ["/bin/sh"]
        #args: ["-c", "mkdir /dataset; curl -O https://storage.googleapis.com/dataset_sabd/posts.dat;
        #         curl -O https://storage.googleapis.com/dataset_sabd/friendships.dat; curl -O https://storage.googleapis.com/dataset_sabd/comments.dat;
        #         mv comments.dat /dataset/comments.dat; mv friendships.dat /dataset/friendships.dat; mv posts.dat /dataset/posts.dat;
        #         mkdir /metrics; touch /metrics/q2-hourly-sliding; touch /metrics/q2-daily-sliding; touch /metrics/q2-weekly-sliding;
        #         touch /metrics/q2-hourly-tumbling; touch /metrics/q2-daily-tumbling; touch /metrics/q2-weekly-tumbling;
        #         mkdir /results; touch /results/q2-hourly-sliding; touch /results/q2-daily-sliding; touch /results/q2-weekly-sliding;
        #          touch /results/q2-hourly-tumbling; touch /results/q2-daily-tumbling; touch /results/q2-weekly-tumbling;
        #          /opt/flink/bin/jobmanager.sh"]
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager