apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: NodePort
  ports:
  - name: rpc
    port: 6123
    nodePort: 30123
  - name: blob
    port: 6124
    nodePort: 30124
  - name: query
    port: 6125
    nodePort: 30125
  - name: ui
    port: 8081
    nodePort: 30081
  selector:
    app: flink
    component: jobmanager